name: Deploy to GitHub Pages

on:
  release: # триггер, который реагирует на события, связанные с релизами
    types: [published] # запускает workflow только когда релиз опубликован

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create versioned directory
        run: |
            mkdir -p public/v${{ github.event.release.tag_name }}
            cp -r ./* public/v${{ github.event.release.tag_name }}/
            rm -rf public/v${{ github.event.release.tag_name }}/.github

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
